name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  confetti: 0.4.0
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_refresh_indicator:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/plane_indicator/
    - assets/ice_cream_indicator/
